import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AlertTriangle, Check, Download, FileCheck2, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PendingSubmitButton } from "@/components/pending-submit-button";
import { canAccessWdoCompliance } from "@/lib/access";
import { getCurrentContext } from "@/lib/current-organization";
import type { CaliforniaWdoActivityExportRecord } from "@/lib/wdo/california/types";
import { californiaWdoActivityLabel } from "@/lib/wdo/california/activity-codes";
import { markWdoBatchFiled } from "../../actions";

type WdoBatchPageProps = {
  params: Promise<{ batchId: string }>;
  searchParams: Promise<{ saved?: string; error?: string }>;
};

export default async function WdoBatchPage({ params, searchParams }: WdoBatchPageProps) {
  const { batchId } = await params;
  const messages = await searchParams;
  const { supabase, organization, userName, membership } = await getCurrentContext();
  if (!canAccessWdoCompliance(membership.role)) redirect("/jobs");
  const [{ data: batch, error: batchError }, { data: items, error: itemError }] = await Promise.all([
    supabase
      .from("wdo_export_batches")
      .select("*")
      .eq("organization_id", organization.id)
      .eq("id", batchId)
      .maybeSingle(),
    supabase
      .from("wdo_export_batch_items")
      .select("id, wdo_activity_id, line_number, normalized_record, serializer_version")
      .eq("organization_id", organization.id)
      .eq("export_batch_id", batchId)
      .order("line_number"),
  ]);
  if (batchError || itemError) throw new Error(batchError?.message ?? itemError?.message);
  if (!batch) notFound();
  const userIds = [batch.created_by, batch.submitted_by].filter(Boolean) as string[];
  const { data: users, error: userError } = userIds.length
    ? await supabase.from("profiles").select("id, full_name, email").in("id", userIds)
    : { data: [], error: null };
  if (userError) throw new Error(userError.message);
  const userNames = new Map((users ?? []).map((user) => [user.id, user.full_name || user.email || "Team member"]));

  return (
    <AppShell organizationName={organization.name} userName={userName} membershipRole={membership.role} active="compliance">
      <div className="page-heading">
        <div><p className="eyebrow">WDO export history</p><h1>{batch.filename}</h1><p>Immutable California WDO batch snapshot and SPCB filing record.</p></div>
        <div className="wdo-heading-actions">
          <Link className="secondary-button" href="/compliance/wdo">Back to WDO queue</Link>
          <Link className="primary-button" href={`/compliance/wdo/batches/${batchId}/download`}><Download size={16} /> Download .TXT</Link>
        </div>
      </div>
      <div className="wdo-batch-page">
        {messages.saved ? <div className="form-alert success"><Check size={17} /> {messages.saved}</div> : null}
        {messages.error ? <div className="form-alert error"><AlertTriangle size={17} /> {messages.error}</div> : null}

        <section className={`wdo-batch-state state-${batch.status}`}>
          {batch.status === "filed" ? <FileCheck2 size={23} /> : <ShieldCheck size={23} />}
          <div>
            <p className="eyebrow">Batch status</p>
            <h2>{batch.status === "filed" ? "Filed with SPCB" : "Generated · filing not yet confirmed"}</h2>
            <p>{batch.status === "filed" ? `Submittal ${batch.spcb_submittal_number} · ${batch.submitted_on}` : "Downloading a TXT does not prove submission. Record the SPCB confirmation after filing."}</p>
          </div>
        </section>

        <section className="wdo-batch-metadata">
          <dl>
            <div><dt>Generated</dt><dd>{new Date(batch.generated_at).toLocaleString()}</dd></div>
            <div><dt>Generated by</dt><dd>{userNames.get(batch.created_by) || "Team member"}</dd></div>
            <div><dt>Activity range</dt><dd>{batch.date_from || "—"} to {batch.date_to || "—"}</dd></div>
            <div><dt>Activities</dt><dd>{batch.number_of_activities}</dd></div>
            <div><dt>Serializer</dt><dd>{batch.serializer_version}</dd></div>
            <div><dt>SHA-256</dt><dd className="checksum-value">{batch.file_checksum_sha256}</dd></div>
            {batch.reexport_reason ? <div><dt>Re-export reason</dt><dd>{batch.reexport_reason}</dd></div> : null}
            {batch.submitted_by ? <div><dt>Submitted by</dt><dd>{userNames.get(batch.submitted_by) || "Team member"}</dd></div> : null}
            {batch.submission_notes ? <div><dt>Submission notes</dt><dd>{batch.submission_notes}</dd></div> : null}
          </dl>
        </section>

        {batch.status !== "filed" ? (
          <section className="wdo-filing-panel">
            <div><p className="eyebrow">SPCB submission tracking</p><h2>Mark this batch as filed</h2><p>Use the acceptance alert from SPCB Connect. The submittal number is evidence of filing.</p></div>
            <form action={markWdoBatchFiled}>
              <input name="batchId" type="hidden" value={batchId} />
              <label>Submitted date<input name="submittedOn" type="date" required /></label>
              <label>SPCB submittal number<input name="submittalNumber" required /></label>
              <label className="field-span-2">Optional notes<textarea name="notes" rows={3} /></label>
              <PendingSubmitButton className="primary-button field-span-2" pendingLabel="Recording filing">Mark batch Filed</PendingSubmitButton>
            </form>
          </section>
        ) : null}

        <section className="wdo-batch-items">
          <div className="section-heading"><div><p className="eyebrow">Immutable export content</p><h2>Included activities</h2></div><span>{items?.length ?? 0} rows</span></div>
          <div className="wdo-batch-item-list">
            <div className="wdo-batch-item-head"><span>Line</span><span>Activity date</span><span>Property</span><span>Activity type</span><span>Inspector license</span></div>
            {(items ?? []).map((item) => {
              const record = item.normalized_record as unknown as CaliforniaWdoActivityExportRecord;
              return (
                <Link className="wdo-batch-item-row" href={`/compliance/wdo/activities/${item.wdo_activity_id}`} key={item.id}>
                  <span>{item.line_number}</span>
                  <span>{record.activityDate}</span>
                  <strong>{record.buildingNumber} {record.street}, {record.city} {record.zipCode}</strong>
                  <span>{record.activityCode} · {californiaWdoActivityLabel(record.activityCode)}</span>
                  <span>{record.inspectorLicenseNumber}</span>
                </Link>
              );
            })}
          </div>
        </section>
      </div>
    </AppShell>
  );
}
