begin;

create extension if not exists pgcrypto;

create type public.membership_role as enum (
  'administrator',
  'manager',
  'office_coordinator',
  'inspector',
  'treatment_coordinator'
);

create type public.job_status as enum (
  'draft',
  'scheduled',
  'in_progress',
  'in_review',
  'ready',
  'delivered',
  'contract_pending',
  'closed',
  'cancelled'
);

create type public.asset_status as enum (
  'pending',
  'ready',
  'failed',
  'archived'
);

create type public.document_status as enum (
  'queued',
  'generating',
  'ready',
  'failed',
  'superseded'
);

create type public.delivery_status as enum (
  'draft',
  'queued',
  'sending',
  'sent',
  'delivered',
  'failed',
  'cancelled'
);

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) > 0),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  timezone text not null default 'America/Los_Angeles',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_memberships (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.membership_role not null,
  status text not null default 'active' check (status in ('invited', 'active', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table public.companies (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  email text,
  phone text,
  website text,
  notes text,
  zoho_crm_account_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, zoho_crm_account_id)
);

create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  company_id uuid references public.companies(id) on delete set null,
  first_name text not null default '',
  last_name text not null default '',
  email text,
  secondary_email text,
  mobile_phone text,
  home_phone text,
  job_title text,
  notes text,
  zoho_crm_contact_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (length(trim(first_name || ' ' || last_name)) > 0),
  unique (organization_id, zoho_crm_contact_id)
);

create table public.properties (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  street_line_1 text not null,
  street_line_2 text,
  city text not null,
  region text not null,
  postal_code text not null,
  country_code text not null default 'US',
  property_type text,
  year_built integer check (year_built is null or year_built between 1600 and 2200),
  latitude numeric(9,6),
  longitude numeric(9,6),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.inspection_jobs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  job_number bigint generated by default as identity,
  legacy_report_id text,
  property_id uuid not null references public.properties(id) on delete restrict,
  prior_job_id uuid references public.inspection_jobs(id) on delete set null,
  assigned_inspector_id uuid references public.profiles(id) on delete set null,
  report_type text not null default 'complete' check (report_type in ('complete', 'limited', 'supplemental', 'reinspection')),
  status public.job_status not null default 'draft',
  inspection_at timestamptz,
  due_at timestamptz,
  summary text,
  internal_notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, job_number),
  unique (organization_id, legacy_report_id)
);

create table public.job_parties (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  inspection_job_id uuid not null references public.inspection_jobs(id) on delete cascade,
  role text not null check (role in ('ordered_by', 'property_owner', 'report_recipient', 'party_of_interest', 'signer')),
  contact_id uuid references public.contacts(id) on delete restrict,
  company_id uuid references public.companies(id) on delete restrict,
  is_primary boolean not null default false,
  receive_report_by_default boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (contact_id is not null or company_id is not null)
);

create table public.findings (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  inspection_job_id uuid not null references public.inspection_jobs(id) on delete cascade,
  code text,
  title text not null,
  description text,
  location text,
  classification text check (classification is null or classification in ('section_i', 'section_ii', 'informational')),
  severity text check (severity is null or severity in ('low', 'moderate', 'high', 'critical')),
  sort_order integer not null default 0,
  status text not null default 'open' check (status in ('open', 'resolved', 'excluded')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.recommendations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  finding_id uuid not null references public.findings(id) on delete cascade,
  description text not null,
  section text check (section is null or section in ('section_i', 'section_ii', 'informational')),
  estimated_cost numeric(12,2) check (estimated_cost is null or estimated_cost >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.assets (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  inspection_job_id uuid references public.inspection_jobs(id) on delete cascade,
  kind text not null check (kind in ('property_photo', 'inspection_photo', 'diagram_source', 'diagram_render', 'report_pdf', 'contract_pdf', 'signed_contract', 'other')),
  storage_provider text not null default 'workdrive' check (storage_provider in ('workdrive', 'supabase', 'r2')),
  provider_file_id text not null,
  provider_folder_id text,
  original_filename text not null,
  content_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  checksum_sha256 text,
  status public.asset_status not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  captured_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (storage_provider, provider_file_id)
);

create table public.evidence_links (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  asset_id uuid not null references public.assets(id) on delete cascade,
  finding_id uuid references public.findings(id) on delete cascade,
  recommendation_id uuid references public.recommendations(id) on delete cascade,
  caption text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  check (finding_id is not null or recommendation_id is not null)
);

create table public.diagrams (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  inspection_job_id uuid not null references public.inspection_jobs(id) on delete cascade,
  source_json jsonb not null default '{}'::jsonb,
  source_asset_id uuid references public.assets(id) on delete set null,
  render_asset_id uuid references public.assets(id) on delete set null,
  version integer not null default 1 check (version > 0),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (inspection_job_id, version)
);

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  inspection_job_id uuid not null references public.inspection_jobs(id) on delete cascade,
  kind text not null check (kind in ('inspection_report', 'proposal', 'contract', 'invoice', 'noc')),
  title text not null,
  created_at timestamptz not null default now(),
  unique (inspection_job_id, kind)
);

create table public.document_versions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  document_id uuid not null references public.documents(id) on delete cascade,
  version integer not null check (version > 0),
  status public.document_status not null default 'queued',
  snapshot jsonb not null default '{}'::jsonb,
  asset_id uuid references public.assets(id) on delete set null,
  checksum_sha256 text,
  generated_by uuid references public.profiles(id) on delete set null,
  generated_at timestamptz,
  failure_message text,
  created_at timestamptz not null default now(),
  unique (document_id, version)
);

create table public.deliveries (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  inspection_job_id uuid not null references public.inspection_jobs(id) on delete cascade,
  document_version_id uuid not null references public.document_versions(id) on delete restrict,
  status public.delivery_status not null default 'draft',
  subject text not null,
  message_body text not null,
  provider text,
  provider_message_id text,
  sent_by uuid references public.profiles(id) on delete set null,
  queued_at timestamptz,
  sent_at timestamptz,
  delivered_at timestamptz,
  failure_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.delivery_recipients (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  delivery_id uuid not null references public.deliveries(id) on delete cascade,
  contact_id uuid references public.contacts(id) on delete set null,
  recipient_type text not null default 'to' check (recipient_type in ('to', 'cc', 'bcc')),
  email text not null,
  display_name text,
  delivery_status text,
  provider_recipient_id text,
  created_at timestamptz not null default now()
);

create table public.provider_references (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  local_entity_type text not null,
  local_entity_id uuid not null,
  provider text not null check (provider in ('zoho_crm', 'zoho_sign', 'zoho_workdrive', 'email')),
  provider_module text,
  provider_record_id text not null,
  sync_status text not null default 'pending' check (sync_status in ('pending', 'synced', 'failed', 'conflict')),
  last_synced_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, provider, provider_record_id),
  unique (organization_id, local_entity_type, local_entity_id, provider)
);

create table public.audit_events (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  request_id text,
  summary text,
  changes jsonb not null default '{}'::jsonb,
  source text not null default 'app',
  created_at timestamptz not null default now()
);

create index organization_memberships_user_idx on public.organization_memberships(user_id, status);
create index companies_organization_idx on public.companies(organization_id, name);
create index contacts_organization_idx on public.contacts(organization_id, last_name, first_name);
create index contacts_company_idx on public.contacts(company_id);
create index properties_organization_idx on public.properties(organization_id, city, postal_code);
create index inspection_jobs_organization_status_idx on public.inspection_jobs(organization_id, status, inspection_at desc);
create index inspection_jobs_property_idx on public.inspection_jobs(property_id);
create index inspection_jobs_inspector_idx on public.inspection_jobs(assigned_inspector_id, inspection_at desc);
create index job_parties_job_idx on public.job_parties(inspection_job_id, role);
create index findings_job_idx on public.findings(inspection_job_id, sort_order);
create index recommendations_finding_idx on public.recommendations(finding_id, sort_order);
create index assets_job_idx on public.assets(inspection_job_id, kind, created_at desc);
create index evidence_links_asset_idx on public.evidence_links(asset_id);
create index evidence_links_finding_idx on public.evidence_links(finding_id);
create index diagrams_job_idx on public.diagrams(inspection_job_id, version desc);
create index documents_job_idx on public.documents(inspection_job_id, kind);
create index document_versions_document_idx on public.document_versions(document_id, version desc);
create index deliveries_job_idx on public.deliveries(inspection_job_id, created_at desc);
create index delivery_recipients_delivery_idx on public.delivery_recipients(delivery_id);
create index provider_references_local_idx on public.provider_references(local_entity_type, local_entity_id);
create index audit_events_organization_created_idx on public.audit_events(organization_id, created_at desc);
create index audit_events_entity_idx on public.audit_events(entity_type, entity_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, email, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.email,
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_organization_member(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.organization_memberships membership
    where membership.organization_id = target_organization_id
      and membership.user_id = (select auth.uid())
      and membership.status = 'active'
  );
$$;

create or replace function public.has_organization_role(
  target_organization_id uuid,
  allowed_roles public.membership_role[]
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.organization_memberships membership
    where membership.organization_id = target_organization_id
      and membership.user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.role = any(allowed_roles)
  );
$$;

create or replace function public.create_organization(organization_name text, organization_slug text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_organization_id uuid;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required';
  end if;

  insert into public.organizations (name, slug)
  values (trim(organization_name), lower(trim(organization_slug)))
  returning id into new_organization_id;

  insert into public.organization_memberships (organization_id, user_id, role, status)
  values (new_organization_id, (select auth.uid()), 'administrator', 'active');

  return new_organization_id;
end;
$$;

create trigger organizations_set_updated_at before update on public.organizations for each row execute procedure public.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();
create trigger memberships_set_updated_at before update on public.organization_memberships for each row execute procedure public.set_updated_at();
create trigger companies_set_updated_at before update on public.companies for each row execute procedure public.set_updated_at();
create trigger contacts_set_updated_at before update on public.contacts for each row execute procedure public.set_updated_at();
create trigger properties_set_updated_at before update on public.properties for each row execute procedure public.set_updated_at();
create trigger jobs_set_updated_at before update on public.inspection_jobs for each row execute procedure public.set_updated_at();
create trigger job_parties_set_updated_at before update on public.job_parties for each row execute procedure public.set_updated_at();
create trigger findings_set_updated_at before update on public.findings for each row execute procedure public.set_updated_at();
create trigger recommendations_set_updated_at before update on public.recommendations for each row execute procedure public.set_updated_at();
create trigger assets_set_updated_at before update on public.assets for each row execute procedure public.set_updated_at();
create trigger diagrams_set_updated_at before update on public.diagrams for each row execute procedure public.set_updated_at();
create trigger deliveries_set_updated_at before update on public.deliveries for each row execute procedure public.set_updated_at();
create trigger provider_references_set_updated_at before update on public.provider_references for each row execute procedure public.set_updated_at();

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_memberships enable row level security;
alter table public.companies enable row level security;
alter table public.contacts enable row level security;
alter table public.properties enable row level security;
alter table public.inspection_jobs enable row level security;
alter table public.job_parties enable row level security;
alter table public.findings enable row level security;
alter table public.recommendations enable row level security;
alter table public.assets enable row level security;
alter table public.evidence_links enable row level security;
alter table public.diagrams enable row level security;
alter table public.documents enable row level security;
alter table public.document_versions enable row level security;
alter table public.deliveries enable row level security;
alter table public.delivery_recipients enable row level security;
alter table public.provider_references enable row level security;
alter table public.audit_events enable row level security;

create policy organizations_member_select on public.organizations
for select to authenticated
using (public.is_organization_member(id));

create policy organizations_admin_update on public.organizations
for update to authenticated
using (public.has_organization_role(id, array['administrator', 'manager']::public.membership_role[]))
with check (public.has_organization_role(id, array['administrator', 'manager']::public.membership_role[]));

create policy profiles_self_select on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

create policy profiles_shared_organization_select on public.profiles
for select to authenticated
using (
  exists (
    select 1
    from public.organization_memberships mine
    join public.organization_memberships theirs on theirs.organization_id = mine.organization_id
    where mine.user_id = (select auth.uid())
      and mine.status = 'active'
      and theirs.user_id = profiles.id
      and theirs.status = 'active'
  )
);

create policy profiles_self_update on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy memberships_member_select on public.organization_memberships
for select to authenticated
using (public.is_organization_member(organization_id));

create policy memberships_admin_insert on public.organization_memberships
for insert to authenticated
with check (public.has_organization_role(organization_id, array['administrator', 'manager']::public.membership_role[]));

create policy memberships_admin_update on public.organization_memberships
for update to authenticated
using (public.has_organization_role(organization_id, array['administrator', 'manager']::public.membership_role[]))
with check (public.has_organization_role(organization_id, array['administrator', 'manager']::public.membership_role[]));

create policy memberships_admin_delete on public.organization_memberships
for delete to authenticated
using (public.has_organization_role(organization_id, array['administrator']::public.membership_role[]));

create policy companies_org_access on public.companies for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy contacts_org_access on public.contacts for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy properties_org_access on public.properties for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy inspection_jobs_org_access on public.inspection_jobs for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy job_parties_org_access on public.job_parties for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy findings_org_access on public.findings for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy recommendations_org_access on public.recommendations for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy assets_org_access on public.assets for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy evidence_links_org_access on public.evidence_links for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy diagrams_org_access on public.diagrams for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy documents_org_access on public.documents for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy document_versions_org_access on public.document_versions for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy deliveries_org_access on public.deliveries for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy delivery_recipients_org_access on public.delivery_recipients for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));
create policy provider_references_org_access on public.provider_references for all to authenticated
using (public.is_organization_member(organization_id))
with check (public.is_organization_member(organization_id));

create policy audit_events_org_select on public.audit_events
for select to authenticated
using (public.is_organization_member(organization_id));

create policy audit_events_org_insert on public.audit_events
for insert to authenticated
with check (public.is_organization_member(organization_id));

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.create_organization(text, text) to authenticated;
revoke all on function public.is_organization_member(uuid) from public;
revoke all on function public.has_organization_role(uuid, public.membership_role[]) from public;
grant execute on function public.is_organization_member(uuid) to authenticated;
grant execute on function public.has_organization_role(uuid, public.membership_role[]) to authenticated;

commit;
